### ISSUE TITLE
Upgrade Board

### ISSUE THREAD

**Issue by PythonLinks** [howerj/forth-cpu#6]
The Nexsys 3 is no longer available. 
The Nexsys 4 is end of life.   It has been renamed the Nexsys a7. 
Only $265 at Diligent, but soon to be discontinued.
https://store.digilentinc.com/nexys-4-ddr-artix-7-fpga-trainer-board-recommended-for-ece-curriculum/

They recommend the Nexsys a7. 
https://reference.digilentinc.com/reference/programmable-logic/nexys-a7/start

Once the new tool chain is in place, it would be great if the software were upgraded to support the Nexys a7.

**Comment by howerj** [comment]
It would be great, but I only have a Nexys 3 board. I do not plan on upgrading this project any time soon.
